services:
  acp-grpc-server:
    extends:
      file: ./docker-compose-base.yaml
      service: acp-grpc-server
    command: [
        "--host=0.0.0.0",
        "--port=50051",
        "--allow-remote-host", # Access to the server is limited to '127.0.0.1' by the 'ports' option
        "--transport-mode=insecure",
      ]
    volumes:
      - "acp_data:/home/container/workdir/"
  ansys-tools-filetransfer:
    extends:
      file: ./docker-compose-base.yaml
      service: ansys-tools-filetransfer
    command:
      [
        "--host=0.0.0.0",
        "--port=50000",
        "--allow-remote-host", # Access to the server is limited to '127.0.0.1' by the 'ports' option
        "--transport-mode=insecure",
      ]
    volumes:
      - "acp_data:/home/container/workdir/"

volumes:
  acp_data:
